### ISSUE TITLE
AdamOptimizer FailedPreconditionError: Attempting to use uninitialized value beta2_power

### ISSUE THREAD

**Issue by amitmac** [amitmac/Question-Answering#2]
Getting error while AdamOptimizer attempt to minimize the loss. Attaching the error log.

```python
Traceback (most recent call last):
  File "assignment4/code/train.py", line 175, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "assignment4/code/train.py", line 170, in main
    qa.train(sess, dataset, save_train_dir, embeddings['glove'])
  File "/workspace/cs224/assignment4/code/qa_model.py", line 440, in train
    train_span_data, mask_context_batch, embeddings)
  File "/workspace/cs224/assignment4/code/qa_model.py", line 294, in optimize
    outputs = session.run(output_feed, input_feed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value beta2_power
         [[Node: beta2_power/read = Identity[T=DT_FLOAT, _class=["loc:@qa/Variable"], _device="/job:localhost/replica:0/task:0/cpu:0"](beta2_power)]]

Caused by op u'beta2_power/read', defined at:
  File "assignment4/code/train.py", line 175, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "assignment4/code/train.py", line 170, in main
    qa.train(sess, dataset, save_train_dir, embeddings['glove'])
  File "/workspace/cs224/assignment4/code/qa_model.py", line 440, in train
    train_span_data, mask_context_batch, embeddings)
  File "/workspace/cs224/assignment4/code/qa_model.py", line 291, in optimize
    self.train_op = self.add_training_op(self.loss)
  File "/workspace/cs224/assignment4/code/qa_model.py", line 275, in add_training_op
    train_op = optimizer.minimize(loss)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 325, in minimize
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 446, in apply_gradients
    self._create_slots([_get_variable_for(v) for v in var_list])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/adam.py", line 129, in _create_slots
    trainable=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1679, in variable
    caching_device=caching_device, name=name, dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 199, in __init__
    expected_shape=expected_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 330, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 1400, in identity
    result = _op_def_lib.apply_op("Identity", input=input, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value beta2_power
         [[Node: beta2_power/read = Identity[T=DT_FLOAT, _class=["loc:@qa/Variable"], _device="/job:localhost/replica:0/task:0/cpu:0"](beta2_power)]]
```

**Comment by amitmac** [comment]
Same type of error happening with MomentumOptimizer, AdagradOptimizer but with GradientDescentOptimizer its working.

**Comment by amitmac** [comment]
Solved at https://github.com/amitmac/Question-Answering/commit/d55969d08ed96176b5caed471ac17738fa7cb7b8

Problem was that train_op was called too late. In case of stateful optimizers (such as AdamOptimizer) minimize creates additional variables. The initializer runs before those variables were created. That's why the exception. Link - https://github.com/tensorflow/tensorflow/issues/8057#issuecomment-310505897
