### ISSUE TITLE
InvalidArgumentError: Shapes of all inputs must match: values[0].shape = [4] != values[1].shape = [1]

### ISSUE THREAD

**Issue by amitmac** [amitmac/Question-Answering#3]
Getting error while stacking tf.range(batch_size) and s (start index of span for each batch) for mismatch in the shapes.

```python
Traceback (most recent call last):
  File "assignment4/code/train.py", line 178, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "assignment4/code/train.py", line 173, in main
    qa.train(sess, dataset, save_train_dir, embeddings['glove'])
  File "/workspace/cs224/assignment4/code/qa_model.py", line 448, in train
    train_span_data, mask_context_batch, embeddings)
  File "/workspace/cs224/assignment4/code/qa_model.py", line 296, in optimize
    outputs = session.run(output_feed, input_feed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shapes of all inputs must match: values[0].shape = [4] != values[1].shape = [1]
         [[Node: qa/stack = Pack[N=2, T=DT_INT32, axis=1, _device="/job:localhost/replica:0/task:0/cpu:0"](qa/range_4, qa/mul)]]

Caused by op u'qa/stack', defined at:
  File "assignment4/code/train.py", line 178, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "assignment4/code/train.py", line 152, in main
    qa = QASystem(encoder, decoder, context_max_len, ques_max_len)
  File "/workspace/cs224/assignment4/code/qa_model.py", line 233, in __init__
    self.setup_system()
  File "/workspace/cs224/assignment4/code/qa_model.py", line 243, in setup_system
    self.start, self.end, self.preds = self.decoder.decode(knowledge_rep, self.batch_size)
  File "/workspace/cs224/assignment4/code/qa_model.py", line 180, in decode
    si = tf.stack([tf.range(batch_size),s], axis=1)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 856, in stack
    return gen_array_ops._pack(values, axis=axis, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 1949, in _pack
    result = _op_def_lib.apply_op("Pack", values=values, axis=axis, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Shapes of all inputs must match: values[0].shape = [4] != values[1].shape = [1]
         [[Node: qa/stack = Pack[N=2, T=DT_INT32, axis=1, _device="/job:localhost/replica:0/task:0/cpu:0"](qa/range_4, qa/mul)]]
```

**Comment by amitmac** [comment]
Try using tensorflow functions for handling dynamic tensors. In this case use tf.tile function. Changing lines where initial value for spans are randomly initialized - 
```python
s = tf.tile([init_span[0]],[batch_size])
e = tf.tile([init_span[1]],[batch_size])
```
